[features]
seeds = false
skip-lint = false
[programs.localnet]
mts_v0_1 = "CnGhbtxaEQiZJFoqUVMhECLZ1a5MPrvYewjqbpMH4gRi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/emasjin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
